# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pl',
            field=models.IntegerField(default=0),
        ),
    ]
