# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_pl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='pl',
            new_name='size',
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
