# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20180121_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playa',
            name='room',
            field=models.CharField(max_length=10000),
        ),
    ]
